# Generated by Django 3.0.7 on 2020-06-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizerapp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
