# Generated by Django 3.0.7 on 2020-06-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizerapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doc',
            field=models.FileField(default=0, upload_to='Appdata'),
            preserve_default=False,
        ),
    ]
