# Generated by Django 3.0.7 on 2020-07-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizerapp', '0006_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscribers',
        ),
    ]
